In [1]:
#creating a vector

In [2]:
#load library
import numpy as np

In [20]:
#create a vector as a row
vector_row = np.array([1, 2, 3])
print(vector_row)

[1 2 3]


In [19]:
#create a vector as a column
vector_column = np.array([[1],
                         [2],
                         [3]])
print(vector_column)
                

[[1]
 [2]
 [3]]


In [6]:
#creating a matrix

In [18]:
import numpy as np
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
print(matrix_object)

[[1 2]
 [1 2]
 [1 2]]


In [13]:
#creating a sparse matrix

In [14]:
import numpy as np
from scipy import sparse

In [15]:
#create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

In [16]:
#create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [17]:
#view sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [21]:
#create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
#create CSR matrix
matrix_large_sparse =sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [23]:
#selecting elements