In [1]:
#Creating a Vector

In [2]:
#load library
import numpy as np

In [20]:
#create a vector as a row
vector_row = np.array([1, 2, 3])
print(vector_row)

[1 2 3]


In [19]:
#create a vector as a column
vector_column = np.array([[1],
                         [2],
                         [3]])
print(vector_column)
                

[[1]
 [2]
 [3]]


In [6]:
#Creating a Matrix

In [18]:
import numpy as np
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
print(matrix_object)

[[1 2]
 [1 2]
 [1 2]]


In [13]:
#Creating a Sparse Matrix

In [14]:
import numpy as np
from scipy import sparse

In [15]:
#create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

In [16]:
#create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [17]:
#view sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [21]:
#create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
#create CSR matrix
matrix_large_sparse =sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [23]:
#Selecting Elements

In [1]:
import numpy as np

In [2]:
#create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

In [3]:
#create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [5]:
#select third element of vector
print(vector[2])

3


In [6]:
#select second row, second column
print(matrix[1, 1])

5


In [7]:
#select all element of a vector
print(vector[:])

[1 2 3 4 5 6]


In [8]:
#select everything up to and including the third element
print(vector[:3])

[1 2 3]


In [9]:
#select everything after the third element
print(vector[3:])

[4 5 6]


In [10]:
#select the last element
print(vector[-1])

6


In [11]:
#select the first two rows and all columns of a matrix
print(matrix[:2, :])

[[1 2 3]
 [4 5 6]]


In [13]:
#select all rows and the second column
print(matrix[:, 1:2])

[[2]
 [5]
 [8]]


In [14]:
#Describing a Matrix

In [15]:
import numpy as np

In [16]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [17]:
#view number of rows and columns
print(matrix.shape)

(3, 4)


In [18]:
#view number of elements(rows * columns)
print(matrix.size)

12


In [19]:
#view number of dimensions
print(matrix.ndim)

2


In [20]:
#Applying Operations to Element

In [3]:
import numpy as np

In [10]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [12]:
#create functions that adds 100 to something
add_100 = lambda matrix: matrix + 100

In [14]:
#create vectorized function
vectorized_add_100 = np.vectorize(add_100)

In [15]:
#apply function to all elements in matrix
print(vectorized_add_100(matrix))

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [16]:
#add 100 to all elements
print(matrix + 100)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [17]:
#Finding the Maximum and Minimum Values

In [18]:
import numpy as np

In [19]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [20]:
#return max element
print(np.max(matrix))

9


In [21]:
#return min element
print(np.min(matrix))

1


In [22]:
#find max element in each row
print(np.max(matrix, axis = 0))

[7 8 9]


In [23]:
#Calculating the Average, Variance, and Standard Deviation

In [24]:
import numpy as np

In [26]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [27]:
#return mean
np.mean(matrix)

5.0

In [28]:
#return variance
np.var(matrix)

6.666666666666667

In [29]:
#return standard deviation 
np.std(matrix)

2.581988897471611

In [30]:
#find the mean value in each column
np.mean(matrix, axis = 0)

array([4., 5., 6.])

In [31]:
#Reshaping Arrays

In [32]:
import numpy as np

In [33]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

In [34]:
#reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [35]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [36]:
#Transposing a Vector or Matrix

In [37]:
import numpy as np

In [38]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [39]:
#transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
#Flattening a Matrix

In [41]:
import numpy as np

In [42]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [43]:
#flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
#Finding the rank of a matrix

In [45]:
import numpy as np

In [46]:
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

In [48]:
#return matrix rank
np.linalg.matrix_rank(matrix)

2

In [49]:
#Calculating the Determinant

In [50]:
import numpy as np

In [51]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

In [53]:
#return determinant of matrix
np.linalg.det(matrix)

0.0

In [54]:
#Getting the Diagonal 

In [55]:
import numpy as np

In [56]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

In [57]:
#return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [58]:
#Calculating the Trace of a Matrix

In [59]:
import numpy as np

In [60]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

In [62]:
#return trace
matrix.trace()

14

In [63]:
#return diagonal and sum
sum(matrix.diagonal())

14

In [64]:
#Finding Eigenvalues and Eigenvectors

In [65]:
import numpy as np

In [66]:
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

In [67]:
#calculate eigenvalues and eigenvectors 
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [68]:
#view eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [69]:
#view eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [70]:
#Calculating Dot Products

In [71]:
import numpy as np

In [78]:
#create two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

In [79]:
#calculate dot product
np.dot(vector_a, vector_b)

32

In [80]:
#calculate dot product
vector_a @ vector_b

32

In [81]:
#Adding and Subtracting Matrices

In [82]:
import numpy as np

In [83]:
matrix_a = np.array([[1, 1, 1],
                   [1, 1, 1],
                   [1, 1, 2]])

In [84]:
matrix_b = np.array([[1, 3, 1],
                    [1, 3, 1],
                    [1, 3, 8]])

In [86]:
#add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [87]:
#subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [88]:
#alternatively
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [89]:
#Multiplying Matrices

In [90]:
import numpy as np

In [91]:
matrix_a = np.array([[1, 1],
                     [1, 2]])

In [92]:
matrix_b = np.array([[1, 3],
                     [1, 2]])

In [93]:
#multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [94]:
#alternatively
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [95]:
#multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

In [96]:
#Inverting a Matrix

In [98]:
import numpy as np

In [99]:
matrix = np.array([[1, 4],
                   [2, 5]])

In [100]:
#calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [101]:
#Generating Random Values 

In [103]:
import numpy as np

In [104]:
#set seed 
np.random.seed(0)

In [106]:
#generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])